### ISSUE TITLE
Could you upload a PDF version to study or print?:)

### ISSUE THREAD

**Issue by FernandoBorea** [rafalab/dsbook#17]
Hello!

I would love to have a PDF version of the program so it would be much easier to study! Please let me know if that is possible:)

Regards,
Fernando.

**Comment by rafalab** [comment]
We are working on this. It is coming soon. Ill announce it on twitter.

**Comment by gwierzchowski** [comment]
Generally some instruction - how to build the book from sources in different formats (including PDF) and what are build dependencies would be very helpfpu to place in some file in repo (like BUILD.md or so).

**Comment by rafalab** [comment]
Here is the pdf:

https://leanpub.com/datasciencebook

**Comment by technocrat** [comment]
Congratulations! I just ordered my copy!




On March 16, 2019 at 1:30:23 PM, Rafael A Irizarry (notifications@github.com)
wrote:

Closed #17 <https://github.com/rafalab/dsbook/issues/17>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rafalab/dsbook/issues/17#event-2208363583>, or mute the
thread
