### ISSUE TITLE
66.3 prob_cond_prob function

### ISSUE THREAD

**Issue by technocrat** [rafalab/dsbook#54]
It is in the .Rmd source code, but not available to the reader of the output. Suggest it be included in `dslabs`

`plot_cond_prob <- function(p_hat=NULL){
  tmp <- mnist_27$true_p
  if(!is.null(p_hat)){
    tmp <- mutate(tmp, p=p_hat)
  }
  tmp %>% ggplot(aes(x_1, x_2, z=p, fill=p)) +
  geom_raster(show.legend = FALSE) +
  scale_fill_gradientn(colors=c("#F8766D","white","#00BFC4")) +
  stat_contour(breaks=c(0.5),color="black")
}`

**Comment by gillsignals** [comment]
Rafa chose to leave this plot code hidden because not all of the `ggplot` functions used are covered in the book. As this format is followed throughout the book when complex plot code is used, and because it clutters the chapter, we choose to leave this code out of the final book. Readers interested in how a given plot was made are welcome to look at the Rmd.

Thanks for your suggestion even though we didn't incorporate it!
